# Documentation: https://github.com/roots/trellis#wordpress-sites
wordpress_sites:
  example.com:
    site_hosts:
      - novoconstruction.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:roots/bedrock.git
    site_install: true
    site_title: Example Site
    admin_user: admin
    admin_password: admin
    admin_email: admin@novoconstruction.dev
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    system_cron: true
    env:
      wp_home: http://novoconstruction.dev
      wp_siteurl: http://novoconstruction.dev/wp
      wp_env: development
      db_name: novo_dev_db
      db_user: novo_dev
      db_password: novocondev
